-- =============================================================================
-- PnP Ecommerce Service - Database Schema
-- Database: H2 (in-memory); SQL is ANSI-compatible and portable to PostgreSQL.
-- =============================================================================

-- Drop in FK-safe order so this script stays idempotent across Spring context
-- reloads (DB_CLOSE_DELAY=-1 keeps the in-memory DB alive between contexts,
-- which would otherwise leave stale rows from prior tests).
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;

-- products
--   Stores the sellable catalogue. Price is kept in cents (R39.99 = 3999) to
--   avoid IEEE 754 floating-point rounding. SKU is the business identifier and
--   must be unique across the catalogue.
CREATE TABLE IF NOT EXISTS products (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name           VARCHAR(255) NOT NULL,
    description    CLOB,
    price          INT          NOT NULL,
    stock_quantity INT          NOT NULL DEFAULT 0,
    sku            VARCHAR(100) NOT NULL,
    created_at     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_products        PRIMARY KEY (id),
    CONSTRAINT uq_products_sku    UNIQUE      (sku),
    CONSTRAINT chk_products_price CHECK       (price          >= 0),
    CONSTRAINT chk_products_stock CHECK       (stock_quantity >= 0)
);

-- orders
--   A customer purchase. Status is constrained to the two supported transitions:
--   CONFIRMED (placed) -> CANCELLED. total_amount mirrors the sum of order_items
--   at placement time; stored in cents to match the product price convention.
CREATE TABLE IF NOT EXISTS orders (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    customer_name  VARCHAR(255) NOT NULL,
    customer_email VARCHAR(255) NOT NULL,
    status         VARCHAR(20)  NOT NULL,
    total_amount   BIGINT       NOT NULL,
    created_at     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_orders         PRIMARY KEY (id),
    CONSTRAINT chk_orders_status CHECK       (status IN ('CONFIRMED', 'CANCELLED')),
    CONSTRAINT chk_orders_total  CHECK       (total_amount >= 0)
);

-- order_items
--   Junction between orders and products. unit_price snapshots the product price
--   at order time so future catalogue price changes cannot alter historical
--   revenue figures.
CREATE TABLE IF NOT EXISTS order_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id   BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity   INT    NOT NULL,
    unit_price INT    NOT NULL,

    CONSTRAINT pk_order_items         PRIMARY KEY (id),
    CONSTRAINT fk_order_items_order   FOREIGN KEY (order_id)   REFERENCES orders(id),
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT chk_order_items_qty    CHECK       (quantity   > 0),
    CONSTRAINT chk_order_items_price  CHECK       (unit_price >= 0)
);

-- Indexes
--   FK columns are indexed to make JOIN lookups in the reporting queries fast.
--   orders.status is indexed for the common WHERE status = 'CONFIRMED' filter.
CREATE INDEX IF NOT EXISTS idx_order_items_order_id   ON order_items (order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_product_id ON order_items (product_id);
CREATE INDEX IF NOT EXISTS idx_orders_status          ON orders      (status);
CREATE INDEX IF NOT EXISTS idx_orders_customer_email  ON orders      (customer_email);
