-- =============================================================================
-- PnP Ecommerce Service - PostgreSQL Schema Init
-- Runs once when the postgres container is first created (via docker-entrypoint-initdb.d).
-- =============================================================================

-- products
CREATE TABLE IF NOT EXISTS products (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name           VARCHAR(255) NOT NULL,
    description    TEXT,
    price          INT          NOT NULL,
    stock_quantity INT          NOT NULL DEFAULT 0,
    sku            VARCHAR(100) NOT NULL,
    created_at     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_products        PRIMARY KEY (id),
    CONSTRAINT uq_products_sku    UNIQUE      (sku),
    CONSTRAINT chk_products_price CHECK       (price          >= 0),
    CONSTRAINT chk_products_stock CHECK       (stock_quantity >= 0)
);

-- orders
CREATE TABLE IF NOT EXISTS orders (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    customer_name  VARCHAR(255) NOT NULL,
    customer_email VARCHAR(255) NOT NULL,
    status         VARCHAR(20)  NOT NULL,
    total_amount   BIGINT       NOT NULL,
    created_at     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_orders         PRIMARY KEY (id),
    CONSTRAINT chk_orders_status CHECK       (status IN ('CONFIRMED', 'CANCELLED')),
    CONSTRAINT chk_orders_total  CHECK       (total_amount >= 0)
);

-- order_items
CREATE TABLE IF NOT EXISTS order_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id   BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity   INT    NOT NULL,
    unit_price INT    NOT NULL,

    CONSTRAINT pk_order_items         PRIMARY KEY (id),
    CONSTRAINT fk_order_items_order   FOREIGN KEY (order_id)   REFERENCES orders(id),
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT chk_order_items_qty    CHECK       (quantity   > 0),
    CONSTRAINT chk_order_items_price  CHECK       (unit_price >= 0)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_order_items_order_id   ON order_items (order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_product_id ON order_items (product_id);
CREATE INDEX IF NOT EXISTS idx_orders_status          ON orders      (status);
CREATE INDEX IF NOT EXISTS idx_orders_customer_email  ON orders      (customer_email);
